apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: tilleggsstonader-alertmanager
  namespace: tilleggsstonader
  labels:
    alertmanagerConfig: tilleggsstonader-alertmanager
spec:
  receivers:
    - name: tilleggsstonader-slack-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#tilleggsstønader-alerts'
          iconEmoji: ":alert:"
          username: "Alertmanager tilleggsstonader"
          sendResolved: false
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ len .Alerts.Firing }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts -}}
            *Alert:* {{ .Labels.alertname }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

            *Consequence:* {{ .Annotations.consequence }}

            *Action:* {{ .Annotations.action }}

            *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
            {{ end }}
          color: |-
            {{ if eq .Status "firing" -}}
              {{ if eq .CommonLabels.severity "warning" -}}
                warning
              {{- else if eq .CommonLabels.severity "critical" -}}
                danger
              {{- else -}}
                #439FE0
              {{- end -}}
            {{ else -}}
              good
            {{- end }}

  route:
    receiver: tilleggsstonader-slack-receiver
    matchers:
      - name: namespace
        matchType: "="
        value: tilleggsstonader
    groupBy:
      - alertname
    groupInterval: 10s
    groupWait: 5s
    repeatInterval: 10m
    routes:
      # Rute for alerts som gjentas maks én gang per dag
      - receiver: tilleggsstonader-slack-receiver
        matchers:
          - name: alert_type
            matchType: "="
            value: tilleggsstonader_daglig
        groupBy:
          - alertname
        groupInterval: 10s
        groupWait: 5s
        repeatInterval: 24h
