apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: tilleggsstonader-alertmanager
  namespace: tilleggsstonader
  labels:
    alertmanagerConfig: tilleggsstonader-alertmanager
spec:
  receivers:
    - name: tilleggsstonader-slack-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: {{slackChannel}}
          iconEmoji: ":alert:"
          username: "Alertmanager tilleggsstonader"
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts -}}
            *Alert:* {{ .Labels.alertname }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

            *Consequence:* {{ .Annotations.consequence }}

            *Action:* {{ .Annotations.action }}

            *Details:*
              {{ range .Labels.SortedPairs }} â€¢ *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
            {{ end }}
          color: |-
            {{ if eq .Status "firing" -}}
              {{ if eq .CommonLabels.severity "warning" -}}
                warning
              {{- else if eq .CommonLabels.severity "critical" -}}
                danger
              {{- else -}}
                #439FE0
              {{- end -}}
            {{ else -}}
              good
            {{- end }}

  route:
    receiver: tilleggsstonader-slack-receiver
    groupBy:
      - alertname
    groupInterval: 10s
    groupWait: 5s
    repeatInterval: 1h
    routes:
      # Rute for alerts som kun skal fyre i arbeidstid
      - receiver: tilleggsstonader-slack-receiver
        matchers:
          - name: alert_type
            matchType: "="
            value: tilleggsstonader_arbeidstid
        activeTimeIntervals:
          - arbeidstid
        groupBy:
          - alertname
        groupInterval: 10s
        groupWait: 5s
        repeatInterval: 1h
      # Rute for alerts som alltid skal fyre
      - receiver: tilleggsstonader-slack-receiver
        matchers:
          - name: alert_type
            matchType: "="
            value: tilleggsstonader_alltid
        groupBy:
          - alertname
        groupInterval: 10s
        groupWait: 5s
        repeatInterval: 1h

  muteTimeIntervals:
    - name: arbeidstid
      timeIntervals:
        - times:
            - startTime: '08:00'
              endTime: '17:00'
          weekdays:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
