apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: tilleggsstonader-alertcond
  namespace: tilleggsstonader
  labels:
    alertmanagerConfig: tilleggsstonader-alerts
spec:
  receivers:
    - name: tilleggsstonader-receiver
      slackConfigs:
        - apiURL:
            name: slack-webhook
            key: apiUrl
          channel: "tilleggsstonader-alerts"
          iconEmoji: ":rotating_light:"
          username: "Tilleggsstonader alert"
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
            *Description:* {{ .Annotations.description }}
            *Details:*
            {{ range .Labels.SortedPairs }} â€¢ *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
            {{ end }}
          color: |-
            {{ if eq .Status "firing" -}}
              {{ if eq .CommonLabels.severity "warning" -}}
                warning
              {{- else if eq .CommonLabels.severity "fatal" -}}
                #611f69
              {{- else if eq .CommonLabels.severity "critical" -}}
                #611f69
              {{- else if eq .CommonLabels.severity "danger" -}}
                danger
              {{- else if eq .CommonLabels.severity "error" -}}
                danger
              {{- else if eq .CommonLabels.severity "notice" -}}
                good
              {{- else if eq .CommonLabels.severity "info" -}}
                #36c5f0
              {{- else -}}
                .CommonLabels.severity
              {{- end -}}
            {{ else -}}
            good
            {{- end }}
  route:
    receiver: tilleggsstonader-receiver
    groupBy:
      - alertname
    matchers:
      - name: alert_type
        matchType: "="
        value: repeating-alert
    groupWait: 5s
    groupInterval: 10s
    repeatInterval: 24h
    activeTimeIntervals:
      - workhours
  timeIntervals:
    - name: workhours
      timeIntervals:
        - weekdays: ["monday:friday"]
          times:
            - startTime: "08:00"
              endTime: "17:00"
