name: Deploy alerts til dev og prod
on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts.yaml'
      - '.nais/alertmanager-config.yaml'
      - '.nais/alertmanager-config-dev.yaml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  apply-alerts:
    name: Apply alerts til dev og prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Deploy alerts til dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts.yaml
      - name: Deploy alertmanager config til dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alertmanager-config.yaml
          VAR: slack_channel="#tilleggsstønader-alerts-dev"
      - name: Deploy alertmanager config til prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alertmanager-config.yaml
          VAR: slack_channel="#tilleggsstønader-alerts"
      - name: Deploy alerts til prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yaml
