name: Deploy alerts til dev og prod
on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts.yaml'
      - '.nais/alertmanager-config.yaml'
      - '.github/workflows/deploy-alerts.yaml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  apply-alerts:
    name: Apply alerts til dev og prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy alerts til dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts.yaml
      - name: Deploy alertmanager config til dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alertmanager-config.yaml
          VARS: .nais/alerts-dev.json
      - name: Deploy alertmanager config til prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alertmanager-config.yaml
          VARS: .nais/alerts-prod.json
      - name: Deploy alerts til prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yaml
